apiVersion: v2
name: harbor-reef-operator
description: Minimal kubernetes operator to revert Harbor cache images to upstream on image pull errors
type: application
version: 1.0.1
appVersion: "1.0.0" # App version should match the version in the VERSION file
