//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// DeepCopyInto copies all properties into another ProxyCache.
func (in *ProxyCache) DeepCopyInto(out *ProxyCache) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of ProxyCache.
func (in *ProxyCache) DeepCopy() *ProxyCache {
	if in == nil {
		return nil
	}
	out := new(ProxyCache)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *ProxyCache) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another ProxyCacheList.
func (in *ProxyCacheList) DeepCopyInto(out *ProxyCacheList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxyCache, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of ProxyCacheList.
func (in *ProxyCacheList) DeepCopy() *ProxyCacheList {
	if in == nil {
		return nil
	}
	out := new(ProxyCacheList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject returns a deep copy as runtime.Object.
func (in *ProxyCacheList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another ProxyCacheSpec.
func (in *ProxyCacheSpec) DeepCopyInto(out *ProxyCacheSpec) {
	*out = *in
	if in.Credentials != nil {
		in, out := &in.Credentials, &out.Credentials
		*out = new(CredentialSpec)
		**out = **in
	}
	if in.ECR != nil {
		in, out := &in.ECR, &out.ECR
		*out = new(ECRSpec)
		**out = **in
	}
}

// DeepCopy returns a deep copy of ProxyCacheSpec.
func (in *ProxyCacheSpec) DeepCopy() *ProxyCacheSpec {
	if in == nil {
		return nil
	}
	out := new(ProxyCacheSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another ProxyCacheStatus.
func (in *ProxyCacheStatus) DeepCopyInto(out *ProxyCacheStatus) {
	*out = *in
	if in.LastReconciled != nil {
		in, out := &in.LastReconciled, &out.LastReconciled
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of ProxyCacheStatus.
func (in *ProxyCacheStatus) DeepCopy() *ProxyCacheStatus {
	if in == nil {
		return nil
	}
	out := new(ProxyCacheStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another CredentialSpec.
func (in *CredentialSpec) DeepCopyInto(out *CredentialSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of CredentialSpec.
func (in *CredentialSpec) DeepCopy() *CredentialSpec {
	if in == nil {
		return nil
	}
	out := new(CredentialSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties into another ECRSpec.
func (in *ECRSpec) DeepCopyInto(out *ECRSpec) {
	*out = *in
}

// DeepCopy returns a deep copy of ECRSpec.
func (in *ECRSpec) DeepCopy() *ECRSpec {
	if in == nil {
		return nil
	}
	out := new(ECRSpec)
	in.DeepCopyInto(out)
	return out
}
