apiVersion: harbor-reef.nvidia.com/v1alpha1
kind: ProxyCache
metadata:
  name: proxy-private
spec:
  type: private
  name: proxy-private
  url: https://private.registry.example.com
  credentials:
    secretName: private-registry-credentials
    usernameKey: username
    passwordKey: password
