apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "harbor-reef-operator.fullname" . }}
  labels:
    {{- include "harbor-reef-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "harbor-reef-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "harbor-reef-operator.labels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "harbor-reef-operator.serviceAccountName" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range . }}
        - name: {{ . | quote }}
        {{- end }}
      {{- end }}
      containers:
        - name: controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: LEADER_ELECTION_ENABLED
              value: {{ ternary "true" "false" .Values.leaderElection.enabled | quote }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LEASE_DURATION
              value: {{ .Values.leaderElection.leaseDuration | quote }}
            - name: RENEW_DEADLINE
              value: {{ .Values.leaderElection.renewDeadline | quote }}
            - name: RETRY_PERIOD
              value: {{ .Values.leaderElection.retryPeriod | quote }}
            {{- if .Values.watchNamespaces }}
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespaces | quote }}
            {{- end }}
            {{- if .Values.harbor.url }}
            - name: HARBOR_URL
              value: {{ .Values.harbor.url | quote }}
            {{- end }}
            {{- if .Values.harbor.adminSecret }}
            - name: HARBOR_ADMIN_SECRET
              value: {{ .Values.harbor.adminSecret | quote }}
            {{- end }}
            {{- if .Values.harbor.adminSecretKey }}
            - name: HARBOR_ADMIN_SECRET_KEY
              value: {{ .Values.harbor.adminSecretKey | quote }}
            {{- end }}
          {{- if .Values.metrics.enabled }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
              protocol: TCP
          {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
