{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "harbor-reef-operator.serviceAccountName" . }}
  labels:
    {{- include "harbor-reef-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.rbac.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "harbor-reef-operator.fullname" . }}
  labels:
    {{- include "harbor-reef-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch","patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create","patch","update","get","list","watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: ["harbor-reef.nvidia.com"]
    resources: ["proxycaches"]
    verbs: ["get","list","watch","patch"]
  - apiGroups: ["harbor-reef.nvidia.com"]
    resources: ["proxycaches/status"]
    verbs: ["get","patch","update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get","list","watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "harbor-reef-operator.fullname" . }}
  labels:
    {{- include "harbor-reef-operator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "harbor-reef-operator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "harbor-reef-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
